FROM python:3.8

ENV PYTHONUNBUFFERED 1

RUN mkdir /zadala

WORKDIR /zadala

COPY ../ .

RUN pip install poetry==1.5.1

RUN poetry install --without dev

ENTRYPOINT ["sh", "/zadala/deployments/entrypoint.sh"]