version: '3.8'
# docker-compose up && docker-compose rm -fsv # run and remove on exit

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 120
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: zadala

  # Database visualizer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    expose:
      - 6379

  zadala-api:
    container_name: zadala
    build: .
    ports:
      - "8000:8000"
    expose:
      - 8000
    environment:
      - DB_NAME=zadala
      - DB_USER=postgres
      - DB_PASS=1
      - DB_HOST=db
      - DB_PORT=5432
      - ENV=prod
      - SECRET_KEY=my-secret
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
