version: '3.8'
#docker-compose up && docker-compose rm -fsv # run and remove on exit

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: zadala

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080