# Generated by Django 3.0.8 on 2020-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('description', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('picture', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
