# Generated by Django 3.0.8 on 2020-08-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('description', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
