# Generated by Django 3.0.8 on 2022-02-12 15:43

from django.db import migrations, models

import authentication.validators


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_provider",
            field=models.CharField(
                choices=[
                    (authentication.validators.AuthProviders["google"], "google"),
                    (authentication.validators.AuthProviders["email"], "email"),
                ],
                default="email",
                max_length=255,
            ),
        ),
    ]
