name: Zadala API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.5.1 && poetry install --only dev
      - name: Lint with flake8
        run: |
          poetry run flake8 .  --statistics
      - name: Typehint with mypy
        run: |
          poetry run mypy .
      - name: Check formatting
        run: poetry run black . --exclude=venv --check
      - name: Check isort imports
        run: |
          poetry run isort . --check-only
  unit-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry==1.5.1 && poetry install
      - name: Run migrations
        run: poetry run python manage.py migrate
      - name: Test with pytest with coverage
        run: poetry run pytest . --cov
