name: Zadala API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  SCA:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pytest mypy isort
      - name: Lint with flake8
        run: |
          flake8 .  --statistics
      - name: Typehint with mypy
        run: |
          mypy .
      - name: Check formatting
        run: black . --exclude=venv --check
      - name: Check isort imports
        run: |
          isort . --check-only
  unit-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run migrations
        run: python manage.py migrate
      - name: Test with pytest with coverage
        run: |
          pytest . --cov