# Generated by Django 3.2.12 on 2022-07-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_products_name_gin_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
